-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- List current monitors and supported resolutions with: hyprctl monitors all

-- All three displays run at scale 1.0, so GDK_SCALE is 1, not Omarchy's
-- default of 2 (which assumes a HiDPI panel). GTK only honors whole numbers.
local omarchy_gdk_scale = 1

hl.env("GDK_SCALE", tostring(omarchy_gdk_scale))

-- Ported from monitors.conf (originally generated by nwg-displays 2026-08-21).
hl.monitor({ output = "eDP-1",    mode = "1920x1200@165.0",  position = "2351x1440", scale = 1.0 })
hl.monitor({ output = "HDMI-A-1", mode = "3440x1440@59.97",  position = "0x0",       scale = 1.0 })
hl.monitor({ output = "DVI-I-1",  mode = "1920x1080@60.0",   position = "3440x360",  scale = 1.0 })
