-- Generated by nwg-displays on 2026-08-21 at 10:22:01. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@165.0",
    position = "2351x1440",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "3440x1440@59.97",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "DVI-I-1",
    mode = "1920x1080@60.0",
    position = "3440x360",
    scale = 1.0
})
